/*
 * Copyright 2025 NXP
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */
 /***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitDEBUG_UARTPins(void);

/*! @name PORT3_18 (number 86), LED_RED
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITLEDSPINS_LED_RED_GPIO GPIO3                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITLEDSPINS_LED_RED_INIT_GPIO_VALUE 1U        /*!<@brief GPIO output initial state */
#define BOARD_INITLEDSPINS_LED_RED_GPIO_PIN 18U              /*!<@brief GPIO pin number */
#define BOARD_INITLEDSPINS_LED_RED_GPIO_PIN_MASK (1U << 18U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITLEDSPINS_LED_RED_PORT PORT3                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITLEDSPINS_LED_RED_PIN 18U                   /*!<@brief PORT pin number */
#define BOARD_INITLEDSPINS_LED_RED_PIN_MASK (1U << 18U)      /*!<@brief PORT pin mask */
                                                             /* @} */

/*! @name PORT3_19 (number 85), LED_GREEN
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITLEDSPINS_LED_GREEN_GPIO GPIO3                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITLEDSPINS_LED_GREEN_INIT_GPIO_VALUE 1U        /*!<@brief GPIO output initial state */
#define BOARD_INITLEDSPINS_LED_GREEN_GPIO_PIN 19U              /*!<@brief GPIO pin number */
#define BOARD_INITLEDSPINS_LED_GREEN_GPIO_PIN_MASK (1U << 19U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITLEDSPINS_LED_GREEN_PORT PORT3                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITLEDSPINS_LED_GREEN_PIN 19U                   /*!<@brief PORT pin number */
#define BOARD_INITLEDSPINS_LED_GREEN_PIN_MASK (1U << 19U)      /*!<@brief PORT pin mask */
                                                               /* @} */

/*! @name PORT3_21 (number 82), LED_BLUE
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITLEDSPINS_LED_BLUE_GPIO GPIO3                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITLEDSPINS_LED_BLUE_INIT_GPIO_VALUE 1U        /*!<@brief GPIO output initial state */
#define BOARD_INITLEDSPINS_LED_BLUE_GPIO_PIN 21U              /*!<@brief GPIO pin number */
#define BOARD_INITLEDSPINS_LED_BLUE_GPIO_PIN_MASK (1U << 21U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITLEDSPINS_LED_BLUE_PORT PORT3                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITLEDSPINS_LED_BLUE_PIN 21U                   /*!<@brief PORT pin number */
#define BOARD_INITLEDSPINS_LED_BLUE_PIN_MASK (1U << 21U)      /*!<@brief PORT pin mask */
                                                              /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitLEDsPins(void);

/*! @name PORT1_7 (number 144), SW2
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITBUTTONSPINS_SW2_GPIO GPIO1               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITBUTTONSPINS_SW2_GPIO_PIN 7U              /*!<@brief GPIO pin number */
#define BOARD_INITBUTTONSPINS_SW2_GPIO_PIN_MASK (1U << 7U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITBUTTONSPINS_SW2_PORT PORT1               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITBUTTONSPINS_SW2_PIN 7U                   /*!<@brief PORT pin number */
#define BOARD_INITBUTTONSPINS_SW2_PIN_MASK (1U << 7U)      /*!<@brief PORT pin mask */
                                                           /* @} */

/*! @name PORT0_6 (number 115), SW3
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITBUTTONSPINS_SW3_GPIO GPIO0               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITBUTTONSPINS_SW3_GPIO_PIN 6U              /*!<@brief GPIO pin number */
#define BOARD_INITBUTTONSPINS_SW3_GPIO_PIN_MASK (1U << 6U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITBUTTONSPINS_SW3_PORT PORT0               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITBUTTONSPINS_SW3_PIN 6U                   /*!<@brief PORT pin number */
#define BOARD_INITBUTTONSPINS_SW3_PIN_MASK (1U << 6U)      /*!<@brief PORT pin mask */
                                                           /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitBUTTONsPins(void);

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitI2CPins(void);

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitSPIPins(void);

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitCANPins(void);

#define PCR_IBE_ibe1 0x01u /*!<@brief Input Buffer Enable: Enables */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#define PCR_IBE_ibe1 0x01u         /*!<@brief Input Buffer Enable: Enables */
#define PCR_PE_pe1 0x01u           /*!<@brief Pull Enable: Enables */
#define PCR_PS_ps1 0x01u           /*!<@brief Pull Select: Enables internal pullup resistor */
#define PORT4_PCR3_MUX_mux00 0x00u /*!<@brief Pin Multiplex Control: Alternative 0 (GPIO) */

/*! @name PORT3_8 (number 98), SMDMA_SPI_SCK
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITSPIPINS_SMARTDMA_SMDMA_SPI_SCK_PORT PORT3               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITSPIPINS_SMARTDMA_SMDMA_SPI_SCK_PIN 8U                   /*!<@brief PORT pin number */
#define BOARD_INITSPIPINS_SMARTDMA_SMDMA_SPI_SCK_PIN_MASK (1U << 8U)      /*!<@brief PORT pin mask */
                                                                          /* @} */

/*! @name PORT3_9 (number 97), SMDMA_SPI_MOSI
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITSPIPINS_SMARTDMA_SMDMA_SPI_MOSI_PORT PORT3               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITSPIPINS_SMARTDMA_SMDMA_SPI_MOSI_PIN 9U                   /*!<@brief PORT pin number */
#define BOARD_INITSPIPINS_SMARTDMA_SMDMA_SPI_MOSI_PIN_MASK (1U << 9U)      /*!<@brief PORT pin mask */
                                                                           /* @} */

/*! @name PORT3_10 (number 96), SMDMA_SPI_MISO
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITSPIPINS_SMARTDMA_SMDMA_SPI_MISO_PORT PORT3                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITSPIPINS_SMARTDMA_SMDMA_SPI_MISO_PIN 10U                   /*!<@brief PORT pin number */
#define BOARD_INITSPIPINS_SMARTDMA_SMDMA_SPI_MISO_PIN_MASK (1U << 10U)      /*!<@brief PORT pin mask */
                                                                            /* @} */

/*! @name PORT3_11 (number 95), SMDMA_SPI_CS
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITSPIPINS_SMARTDMA_SMDMA_SPI_CS_PORT PORT3                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITSPIPINS_SMARTDMA_SMDMA_SPI_CS_PIN 11U                   /*!<@brief PORT pin number */
#define BOARD_INITSPIPINS_SMARTDMA_SMDMA_SPI_CS_PIN_MASK (1U << 11U)      /*!<@brief PORT pin mask */
                                                                          /* @} */

/*! @name PORT3_13 (number 91), SENSOR_INT1
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITSPIPINS_SMARTDMA_SENSOR_INT1_GPIO GPIO3                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITSPIPINS_SMARTDMA_SENSOR_INT1_GPIO_PIN 13U              /*!<@brief GPIO pin number */
#define BOARD_INITSPIPINS_SMARTDMA_SENSOR_INT1_GPIO_PIN_MASK (1U << 13U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITSPIPINS_SMARTDMA_SENSOR_INT1_PORT PORT3                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITSPIPINS_SMARTDMA_SENSOR_INT1_PIN 13U                   /*!<@brief PORT pin number */
#define BOARD_INITSPIPINS_SMARTDMA_SENSOR_INT1_PIN_MASK (1U << 13U)      /*!<@brief PORT pin mask */
                                                                         /* @} */

/*! @name PORT4_3 (number 24), SENSOR_INT2
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITSPIPINS_SMARTDMA_SENSOR_INT2_GPIO GPIO4               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITSPIPINS_SMARTDMA_SENSOR_INT2_GPIO_PIN 3U              /*!<@brief GPIO pin number */
#define BOARD_INITSPIPINS_SMARTDMA_SENSOR_INT2_GPIO_PIN_MASK (1U << 3U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITSPIPINS_SMARTDMA_SENSOR_INT2_PORT PORT4               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITSPIPINS_SMARTDMA_SENSOR_INT2_PIN 3U                   /*!<@brief PORT pin number */
#define BOARD_INITSPIPINS_SMARTDMA_SENSOR_INT2_PIN_MASK (1U << 3U)      /*!<@brief PORT pin mask */
                                                                        /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitSPIPins_SmartDMA(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
